FROM golang:1.20.5-bullseye AS build-env

ARG BRANCH_NAME

WORKDIR /go/src/github.com/anryton/

RUN git clone "https://github.com/anryton/anryton.git"

WORKDIR /go/src/github.com/anryton/anryton

RUN apt-get update -y

RUN git checkout ${BRANCH_NAME}

RUN make build

FROM golang:1.20.5-bullseye

RUN apt-get update \ 
&& apt-get install jq=1.6-2.1 -y --no-install-recommends \ 
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

WORKDIR /go/src/github.com/anryton/anryton

COPY ./init-node.sh .

# perms to make init-node.sh executable
RUN chmod +x init-node.sh

COPY --from=build-env /go/src/github.com/anryton/anryton/build/anrytond /usr/bin/anrytond

EXPOSE 26656 26657 1317 9090 8545 8546

CMD ["sh", "./init-node.sh"]
